### Total distance of courier with id value 1
GET {{host}}/v1/couriers/1/total-distance

### Total distance of courier with id value 2
GET {{host}}/v1/couriers/2/total-distance

### Should add courier location
POST {{host}}/v1/couriers/locations
Content-Type: application/json

{
    "courierId": 1,
    "time": "2018-02-05T11:59:11.332Z",
    "location": {
        "latitude": 40.9923308,
        "longitude": 29.1244229
    }
}

### Should not add courier location
POST {{host}}/v1/couriers/locations
Content-Type: application/json


{
  "courierId": 1,
  "time": "2018-02-05T11:59:11.332Z",
  "location": {
    "latitude": 12312.12,
    "longitude": 22312.12
  }
}

###
